### ISSUE TITLE
Moves page needs scroll-padding to compensate for sticky table header

### ISSUE THREAD

**Issue by tigt** [tigt/ptv#27]
<img width="903" alt="Screen Shot 2021-09-25 at 1 56 43 PM" src="https://user-images.githubusercontent.com/8072522/134781401-f7aa57fb-ec8c-4e2b-9278-bb142c0f056b.png">

```css
html {
  scroll-padding: 2em; /* or whatever that header is functionally as tall as */
}
```
